server:
  port: 5001

spring:
  profiles:
    active: dev
  application:
    name: SERVICE-PROVIDER
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://linaxhua.cn:33306/pesystem?useUnicode=true&characterEncoding=utf8
    username: pesystem
    password: PEsystem@=
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.fzn.pesystem.common.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  instance:
    instance-id: provider-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

info:
  app.name: provider
  company.name: www.pesystem.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.49:4001/eureka