server:
  port: 7001
spring:
  profiles:
    active: dev
  application:
    name: SERVICE-GATEWAY
eureka:
  instance:
    instance-id: zuul-${server.port}
    prefer-ip-address: true
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator
zuul:
  prefix: /api # 路由前缀
  sensitive-headers: # Cookie,Set-Cookie,Authorization
  routes:
    service-uaa: /uaa/**
    service-user: /user/**
    service-case: /case/**
    service-depart: /depart/**
    service-provider: /provider/**

# 下面的设置针对超大文件上传（比如500M），提升了超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 3000

ribbon:
  ConnectionTimeout: 2000
  ReadTimeout: 30000
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.49:4001/eureka