server:
  port: 6001
spring:
  profiles:
    active: dev
  application:
    name: SERVICE-UAA
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: mysql
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.glriverside.microservice.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  instance:
    instance-id: uaa-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pesystem?useUnicode=true&characterEncoding=utf8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/pesystem?useUnicode=true&characterEncoding=utf8
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.49:4001/eureka
