server:
  port: 10001

spring:
  profiles:
    active: dev
  application:
    name: SERVICE-CASE
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

eureka:
  instance:
    instance-id: case-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

aliyun:
  oss:
    file:
      endpoint: ############
      keyid: #############
      keysecret: ###########
      bucketname: ###########

---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka
swagger:
  auth_server: http://localhost:7001/api/uaa/oauth/token
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.49:4001/eureka
swagger:
  auth_server: http://##########:7001/api/uaa/oauth/token
